### ISSUE TITLE
rtsp-face-sdk

### ISSUE THREAD

**Issue by 373137461** [mymagicpower/AIAS#1]
Calvin大神您好，请问可以提供一下rtsp-face-sdk中用到的lib吗，me.calvin.aias.FaceDetect找不到，不胜感激

**Comment by mymagicpower** [comment]
不就放在lib目录下吗？









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mymagicpower/AIAS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 下午4:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mymagicpower/AIAS] rtsp-face-sdk (#1)





 
Calvin大神您好，请问可以提供一下rtsp-face-sdk中用到的lib吗，me.calvin.aias.FaceDetect找不到，不胜感激
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 373137461** [comment]
谢谢，找到了。我引入的是face_sdk_cpu中用的aais-face-lib-0.1.0.jar，文件名一样所以忽略了lib里的文件
